let jobs = [ 
 {
    title: "ECD Learnership 2026 - ETDP SETA (NQF 4 & 5)",
    company: "ETDP SETA & Dept of Basic Education",
    location: "Nationwide - All Provinces",
    type: "12-18 Months Learnership - R3000pm Stipend",
    closing: "2026-12-31 - Continuous Intake",
    description: "Real and verified ECD Learnership for 2026 funded by ETDP SETA. Earn NQF Level 4 or 5 in Early Childhood Development while working in registered preschools. Stipend R3000 per month, free tuition, no fees. Requirements: SA citizen, 18-35, unemployed, Grade 10-12/Matric, passion for children, clean criminal record and must pass Sexual Offences Register check. Learn child development, health & safety, play-based learning. Apply via SAYouth.mobi (search ECD), ETDP SETA, TVET Colleges, SmartStart. Never pay to apply.",
    link: "https://sayouth.mobi",
    verified: "ETDP SETA Official - No Fee - R3000 Stipend",
  },
 {
    title: "SARS Customs & Excise Cadet Learnership X80 - 12 Months Contract (11620)",
    company: "South African Revenue Service (SARS)",
    location: "Nationwide - All Provinces - SARS Branches & Border Posts",
    type: "Learnership X80 - 12 Months - Stipend Provided - Grade 12",
    closing: "Apply ASAP - Posted Sept 2026",
    description: "SARS OFFICIALLY OPEN - Customs & Excise Cadet Learnership Programme X80 Positions - 12 Months Contract Ref 11620. Successfully applied 25 Sept 2026 - Application Status: Your application has been sent. Requirements: South African Citizen, Matric / Grade 12 / NQF Level 4, No criminal record, Willing to learn Customs & Excise. Duties: Assist with customs inspections, border control support, excise duties, client service. HOW TO APPLY: Create profile on SAP SuccessFactors SARS e-Recruitment https://sars.erecruit.co.za - Complete My Candidate Profile - Upload CV and Cover Letter (Required), Set Current Salary to 0 if unemployed, Save profile until green 'Last Saved' appears, then go to JOB SEARCH and apply. No fees - Official SARS portal only.",
    link: "https://sars.erecruit.co.za",
    verified: "VERIFIED - Official SARS SuccessFactors - Application Sent 25 Sept 2026",
 },
{
    title: "Capitec Bank Better Champion Learnership Pipeline",
    company: "Capitec Bank",
    location: "Nationwide - All Provinces - Various Branches",
    type: "Learnership - 12 Months - No Experience Needed",
    closing: "Open - Apply ASAP - Pipeline",
    description: "Capitec Bank Better Champion Learnership is OFFICIALLY OPEN via SuccessFactors. Duties: Welcome and assist clients, coordinate queue and branch flow, assist clients at ATMs. Requirements: Grade 12 / National Certificate (Vocational), No previous experience needed - fast learner, Basic calculation skills, Good communication skills, Computer literacy MS Word, Excel, Outlook. You must complete the short assessment on the official Capitec careers page after applying. Official application ONLY via careers.capitecbank.co.za -> search 'Bank Better Champion'. No fees. After applying you will see 'Thank you for completing your application' screen with View Profile button.",
    link: "https://careers.capitecbank.co.za",
    verified: "VERIFIED - Official Capitec Portal successfactors.eu - Free Application",
  },
 {
    title: "NSFAS Bursary 2027 - Applications OPEN",
    company: "National Student Financial Aid Scheme (DHET)",
    location: "All Public Universities & TVET Colleges - Nationwide",
    type: "Full Bursary - Government Funded",
    closing: "2026-10-31 - Closing 31 Oct 2026",
    description: "NSFAS 2027 applications officially opened 18 Sept 2026 by Minister Buti Manamela. For SA citizens studying at public universities/TVET colleges in 2027. Covers full tuition, registration, accommodation, transport, living allowance and learning materials. Income threshold: R350k per year combined (R600k for disability), SASSA recipients auto-qualify. Apply FREE online only at my.nsfas.org.za - create myNSFAS account with ID, phone, email, complete info, upload documents, press SUBMIT and save reference number. Never share OTP or pay anyone. Apply early to avoid errors. Outcomes in Dec 2026.",
    link: "https://my.nsfas.org.za",
    verified: "NSFAS Official - Launched 18 Sept 2026 - DHET - Free Application",
  }, 
 {
    title: "Sales Consultant - PJK - SHOPRITE SENEKAL",
    company: "Smollan",
    location: "Senekal, Free State",
    type: "Sales Consultant / Field Marketer",
    closing: "2026-10-15 - Apply ASAP (SA Youth - Posted 15 Sept)",
    description: "Smollan is hiring Sales Consultant for PJK at Shoprite Senekal. Posted on SAYouth.mobi 15 September 2026 (9 days ago). Duties: Promote PJK products in Shoprite store, merchandising, sales, customer service, stock management. Requirements: SA Citizen 18-34, Matric/Grade 11-12, good communication, willing to work retail hours, sales experience advantageous. Apply via SA Youth.mobi - FREE, no fee. Data needed to apply.",
    link: "https://sayouth.mobi/View/Opportunity",
    verified: "SA Youth.mobi - Smollan - Posted 15 Sept 2026",
  },
 {
    title: "ECD Learnership - Community & NGO Providers",
    company: "SmartStart / Save The Children / Local ECD Centres",
    location: "Limpopo (Vhembe District included), Gauteng, KZN, WC",
    type: "12 Months - Stipend R1500 - R3500",
    closing: "Open Now",
    description: "Community-based ECD learnerships via accredited providers like SmartStart and NGOs. For youth passionate about early learning (birth to 5 years). Work-integrated learning in daycares and preschools. Requires CV, certified ID, Matric or Grade 10-11 report, proof of residence. Legit providers will never ask for money and will always do background checks. Check with your nearest Thusong Centre or TVET for local intake.",
    link: "https://www.etdpseta.org.za",
    verified: "Accredited Provider - Verify at ETDP SETA",
  },
 {
    title: "Tourism Monitors Programme 2026/27",
    company: "Department of Tourism and SANParks",
    location: "South Africa - Various National Parks",
    type: "12 Months Contract - R200 per day",
    closing: "2026-09-30",
    description: "The Department of Tourism and SANParks invite unemployed youth aged 18-35 with Matric/Grade 12 to apply for the Tourism Monitors Programme. 12-month programme based in National Parks including Tsitsikamma, Addo Elephant, Camdeboo, Mountain Zebra, Golden Gate, Marakele, Mapungubwe, Kruger Marula Region, Knysna, Wilderness, Table Mountain, Kgalagadi, Augrabies, Richtersveld and more. Requirements: SA Citizen, reside within 30km of park, willing to work weekends, arrange own accommodation/transport. Fitness assessment: 2.4km run and 25 push-ups. Apply via SAYouth.mobi. Upload certified ID, qualifications and proof of residence.",
    link: "https://sayouth.mobi",
    verified: "Department of Tourism - SANParks",
  },
 {
    title: "Pool Bus Driver (P14) - 20 Positions",
    company: "Maluti Bus Service",
    location: "Phuthaditjhaba / Harrismith / Bethlehem, Free State",
    type: "Pool Driver - Training Then Pool Placement",
    closing: "2026-10-06",
    description: "Internal Advertisement - Maluti Bus Service is recruiting 20 Pool Bus Drivers (P14) to be trained and placed in the Company's Bus Driver Pool. This is NOT immediate permanent appointment. Successful candidates will undergo prescribed driver training and competency assessment. Appointment only when operational need arises. Location: Phuthaditjhaba, Harrismith, Bethlehem. Reports to: Operations Manager. Ref: Pool Bus Driver 22092026. Requirements: Grade 8 or equivalent, Valid Code EC / EC1 license, Valid PrDP, Min 2 years Bus/Heavy vehicle driving, good numerical and interpersonal skills, good working history. Must be able to work shifts, reliable and trustworthy, good health, willing to work between 3 areas. Application: Email CV to recruitment@malutibs.co.za. Shortlisted candidates will undergo vetting: qualifications, employment history, criminal, credit/financial, reference and security vetting.",
    link: "mailto:recruitment@malutibs.co.za",
    verified: "Maluti Bus Service - recruitment@malutibs.co.za - Closing: 06 Oct 2026",
  },
 {
    title: "Free State Provincial Government Bursary 2027 - FULL TIME",
    company: "Office of the Premier - Free State",
    location: "Free State Province (Study anywhere in SA)",
    type: "Full Bursary - Covers All",
    closing: "2026-11-13",
    description: "Office of the Premier calling unemployed youth 18-35 in Free State to apply for 2027 Full-Time Bursary. Covers tuition, accommodation, textbooks, meals, transport, living allowance. For Degree/Diploma at accredited HEI. Priority: STEM, Commerce/Finance/Economics/Accounting, Psychology, Social Sciences, Aviation, Public Governance. Requirements: SA citizen, FS resident, 18-35, unemployed, household income <R600k, not receiving other gov funding. Apply online at freestateonline.fs.gov.za/bursaries/ or hand deliver to 124 Nelson Mandela Drive, Westdene, Bloemfontein. Enquiries: bursariesfs@fspremier.gov.za / 0657425935.",
    link: "https://www.freestateonline.fs.gov.za/bursaries/",
    verified: "Office of the Premier FS - Official - Closes 13 Nov 2026 16:00",
  },
 {
    id: "sanbi-lowveld-isep-sayouth-2026",
    title: "Lowveld National Botanical Garden - Integrated Service Excellence Programme",
    company: "SANBI via SA Youth",
    location: "Mpumalanga - Nelspruit",
    type: "Youth Opportunity",
    closing: "2026-09-18",
    category: "Tourism",
    description: "SAYouth.mobi opportunity. Search 'Integrated Service Excellence Programme' on SA Youth if link fails. Register free no data needed on sayouth.mobi. Location pin Lowveld National Botanical Garden.",
    link: "https://sayouth.mobi/p/yxmkrv78/o/2141344",
    verified: "Verified Shared via SAYouth - Free 0800 72 72 72 - 18 Sep 2026",
  },
 {
    id: "dha-cadet-learnership-2026-limpopo-x5",
    title: "Cadet Learnership Programme 2026/2027 (12 Months) - Limpopo X5 Posts",
    company: "Department of Home Affairs",
    location: "Limpopo - Polokwane, Giyani, Jane Furse, Thohoyandou, Mokopane",
    type: "Learnership - 12 Months",
    closing: "2026-09-18",
    category: "Government Learnership",
    description: "PSV Circular 32 of 2026. Chief Directorate Learning & Development. Stipend R4 500 per month. National Senior Certificate (Matric) NQF 4. Centres: Polokwane HRMC 58/26/9a, Giyani 58/26/9b, Jane Furse 58/26/9c, Thohoyandou 58/26/9d, Mokopane 58/26/9e. Apply with Z83 and CV.",
    link: "https://www.dha.gov.za/",
    verified: "Verified - DPSA Circular 32 of 2026 - Official DHA - 18 Sep 2026 at 16:00",
  },
 {
    id: "dha-cadet-learnership-2026-kzn-x6",
    title: "Cadet Learnership Programme 2026/2027 - KZN X6 Posts",
    company: "Department of Home Affairs",
    location: "KZN - Ixopo, New Hanover, Eshowe, Estcourt, Umgeni, Richards Bay",
    type: "Learnership - 12 Months",
    closing: "2026-09-18",
    category: "Government Learnership",
    description: "PSV Circular 32 of 2026 Post 32/120 Stipend R4 500. Centres: Ixopo HRMC 58/26/7a, New Hanover 58/26/7b, Eshowe 58/26/7c, Estcourt 58/26/7d, Umgeni 58/26/7e, Richards Bay 58/26/7f. National Senior Certificate Matric. Email Cadetrecruitmentkzn@dha.gov.za",
    link: "https://www.dha.gov.za/",
    verified: "Verified - DPSA Circular 32 of 2026 - 18 Sep 2026",
  },
 {
    id: "dha-cadet-learnership-2026-northwest-x5",
    title: "Cadet Learnership Programme 2026/2027 - North West X5 Posts",
    company: "Department of Home Affairs",
    location: "North West - Klerksdorp X4, Mankwe X1",
    type: "Learnership - 12 Months",
    closing: "2026-09-18",
    category: "Government Learnership",
    description: "POST 32/116 Cadet Learnership North West X5. Stipend R4 500 per month. Klerksdorp Ref HRMC 58/26/3a X4 Posts, Mankwe Ref HRMC 58/26/3b X1 Post. Matric required. Enquiries Ms Makgabo Kobola (012) 406 7078 makgabo.kobola@dha.gov.za",
    link: "https://www.dha.gov.za/",
    verified: "Verified - PSV Circular 32 of 2026 - North West",
  },
 {
    title: "Administrative Controller: Food Safety",
    company: "Clover",
    location: "South Africa",
    type: "Permanent",
    closing: "2026-09-03",
    description: "Clover SA (Top Employer South Africa 2026) is hiring Administrative Controller: Food Safety - Ref CLO260827-5. Department: Production. 01 Position. Job Type: Permanent. Closing Date: 03 September 2026. Apply via Clover Careers portal.",
    link: "https://www.clover.co.za/careers - Ref CLO260827-5",
    verified: "Clover Careers - Top Employer 2026"
  },
 {
    id: "festive-millwright-2026",
    title: "Millwright Apprenticeship (36 Months)",
    company: "Festive - Astral Operations Limited",
    location: "Olifantsfontein, Gauteng - Processing Plant",
    type: "Apprenticeship - 36 Months Fixed Term",
    closing: "2026-09-13",
    category: "Artisan Apprenticeship",
    description: "Festive, a division of Astral Operations Limited, aims to provide Apprentices with opportunity to obtain training, gain knowledge and acquire practical experience in transitioning from student to employee for a fixed period of 36 months at Processing Plant in Olifantsfontein. Vacancies for: Millwrights, Electricians, Fitters. Ideal candidates must be young, energetic, qualified N3 students with a passion to become an artisan.",
    requirements: [
     "Grade 12 (Matric) with Mathematics and Science OR Technical Matric",
     "National Technical Certificate - N3 or higher in Millwright engineering discipline",
     "Ambitious and dedicated - willing to use opportunities industry has to offer",
     "Must be a team player",
     "High energy level and action orientated",
     "Mental alertness, analytical and problem solving skills",
     "Pay attention to detail and conceptual skills",
     "Must be in possession of a tool box including tools"
   ],
   duties: [
     "Participate in formal training plan for the apprenticeship",
     "Perform duties required and make reasonable progress to achieve competencies",
     "Undertake and attend any training or assessment related to training plan",
     "Keep logbook in possession and produce when requested",
     "Maintain, repair & optimise plant & associated devices under guidance of qualified Artisans",
     "Obey all workplace health and safety including dress code"
    ],
    link: "https://www.trending-talent.com",
    applyLink: "https://www.trending-talent.com",
    howToApply: "Apply online via Trendi - www.trending-talent.com - Search Festive Apprenticeship. Closing: 13 September 2026",
    verified: true,
    featured: true
  },
 {
    id: "matjhabeng-meter-2026",
    title: "Meter Readers (36 Positions)",
    company: "Matjhabeng Municipality",
    location: "Welkom, Free State",
    type: "Full-time Permanent",
    salary: "R162 156 - R184 620 p.a (Excluding benefits)",
    postLevel: "16/15",
    closing: "2026-09-18",
    category: "Municipality Jobs",
    description: "Matjhabeng Municipality invites applications for Meter Readers (36 Positions). Reading meters (Taking photos compulsory), ensuring all meters are read correctly, reporting illegal connections, handling consumer disputes. Must have ability to function under pressure.",
    requirements: ["Grade 10", "Valid Code B driver's license will be an advantage", "Computer literacy (MS Word, Excel)", "Must be able to read and write clearly, add and subtract numbers", "Basic Knowledge of Computer", "Electrical background is an advantage", "Willing to work overtime when required"],
    duties: ["Reading meters (Taking photos compulsory)", "Ensuring all meters are read correctly", "Recording reading of all meters listed in the reading sheet", "Providing reason for all unread meters", "Reporting illegal connections and abnormalities", "Verifying meter/s as requested", "Reporting faulty meters, leaks and pipe bursts"],
    link: "https://matjhabeng.co.za",
    applyLink: "https://matjhabeng.co.za",
    howToApply: "Forward application to: The Senior Manager Human Resources, P.O Box 708 Welkom 9460 or hand deliver to Room 5, 3rd Floor, Welkom. Apply online: https://matjhabeng.co.za. Enquiries: Recruitment office @ (057) 492 1363",
    verified: true,
    featured: true
  },
 {
    id: "matjhabeng-general-2026",
    title: "General Workers (150 Positions)",
    company: "Matjhabeng Municipality",
    location: "Welkom, Free State",
    type: "Full-time Permanent",
    salary: "R153 384 - R159 996 p.a (Excluding benefits)",
    postLevel: "18/17",
    closing: "2026-09-18",
    category: "Municipality Jobs",
    description: "Matjhabeng Municipality invites applications for General Workers (150 Positions). Key duties: Perform general labour duties such as cleaning, digging, loading/unloading materials, and maintain municipal facilities. Operate basic tools and equipment. Follow instructions from supervisors and adhere to safety regulations.",
    requirements: ["Grade 10", "Conversant in local languages", "Must be physically fit to perform duties", "Driver's license would be an added advantage", "Preference will be given to applicants residing within the Municipal area"],
    duties: ["Perform general labour duties - cleaning, digging, loading/unloading", "Maintain municipal facilities", "Operate basic tools and equipment", "Follow instructions from supervisors", "Adhere to safety regulations and municipal policies"],
    link: "https://matjhabeng.co.za",
    applyLink: "https://matjhabeng.co.za",
    howToApply: "Forward complete application form and comprehensive CV with certified copies of qualifications to: The Senior Manager Human Resources, P.O Box 708 Welkom 9460 or hand it to Municipal Building, Municipal Main Building, Room 5, 3rd Floor, Welkom. Or apply online via https://matjhabeng.co.za. Enquiries: (057) 492 1363",
    verified: true,
    featured: true
  }, 
 {
    id: "JR105826",
    title: "UIF Skills Programme - Pick n Pay Hypermarkets",
    company: "Pick n Pay",
    location: "South Africa (Nationwide)",
    type: "Learnership - 6 Months",
    stipend: "R2000 per month",
    closing: "2026-09-30",
    category: "Retail Learnership",
    description: "Kick-start your career with Pick n Pay's UIF Skills Programmes. Gain practical workplace experience and retail skills through structured learning and on-the-job training. Duration: 6 Months. Stipend: R2,000 per month. Learning Model: Blended Learning (Online + In-store). Minimum: Grade 12, Aged 18-40, SA Citizen, Unemployed. Streams: MASTERCUT (Butchery skills), FRESHRIZE (Bakery Talent), ALL ROUNDERS (Retail Frontline). What You Will Gain: Structured learning, Practical experience, Coaching from Store Mentors, Customer service skills.",
    requirements: ["Grade 12", "Aged 18-40 years", "South African citizen", "Currently unemployed", "Passion for food, retail and customer service", "Willing to work retail hours including weekends"],
    documents: ["Updated CV", "Certified copy of South African ID", "Certified copy of Matric certificate"],
    link: "https://picknpay.wd3.myworkdayjobs.com/en-US/PNP_Careers/job/UIF-Skills-Programme--Pick-n-Pay-Hypermarkets_JR105826",
    applyLink: "https://picknpay.wd3.myworkdayjobs.com/en-US/PNP_Careers/job/UIF-Skills-Programme--Pick-n-Pay-Hypermarkets_JR105826",
    verified: true,
    featured: true
  },
 { 
    title: "BEE Chamber Learnership - All Fields",
    company: "BEE Chamber",
    location: "South Africa - All Provinces",
    type: "Learnership - 12 Months",
    closing: "2026-12-31",
    description: "Free accredited learnerships: Manufacturing, Business Admin, Food Processing, Agriculture. Stipend paid. Requirements: SA Citizen, Grade 10-12, Age 18-35, Unemployed. No fees. Includes NQF Certificate.",
    link: "https://bee.co.za/",
    verified: "Verified - Official BEE Chamber Portal - Apply Direct"
  },
 {
    title: "Admin Assistant - VKB Mechanisation",
    company: "VKB Group",
    location: "Douglas, Northern Cape",
    province: "Northern Cape",
    town: "Douglas",
    type: "On-site | 6 Days (Mon-Sat) | Permanent",
    salary: "Market Related",
    ref: "VKB Admin Assistant - Douglas | Closing: 15 Sept 2026",
    desc: "VKB Group is hiring Admin Assistant for Mechanisation Branch in Douglas. Grade 12/NQF4 required. Computer literate (MS Office). Workshop/spares experience is a recommendation. Must be willing to work 6 days Mon-Sat. Duties: Handle petty cash transactions, end-of-day reconciliation & banking, process claims, receive supplier deliveries per policy, liaise with internal/external customers, maintain safety docs & manage job cards, general admin & workshop coordination. Good communication skills needed. VKB is Equal Opportunity Employer - People with Disabilities encouraged.",
    link: "https://www.vkb.co.za/careers/",
    verified: "✅ Verified - VKB Official Portal - No Fees - Equal Opportunity",
    posted: "2026/08/03",
    closing: "2026/09/15"
  },
 {
    title: "Electrician / Millwright",
    company: "Supreme Poultry (CBH)",
    location: "Botshabelo Processing Plant, Free State",
    province: "Free State",
    town: "Botshabelo",
    type: "On-site, Full-time | Shift work + Standby",
    salary: "Market Related - Permanent",
    ref: "CBH_ELEC-28/08/2026 + Your Name Surname | Closing: 11 September 2026",
    desc: "Supreme Poultry is hiring Electrician/Millwright at Botshabelo Plant. Requirements: Section 13 Trade Test Certificate, Category B ammonia refrigeration, 3-5 years poultry industry experience, strong electrical compliance & refrigeration knowledge. Duties: Maintain poultry processing machinery, service industrial ammonia refrigeration, troubleshoot automated equipment, urgent breakdown repairs, electrical inspections, preventive maintenance, record work done. Must work shifts, standby & overtime. Apply via HR email with reference in subject.",
    link: "mailto:lichibase@cbh.africa?subject=CBH_ELEC-28/08/2026 - Your Name Surname",
    verified: "✅ Verified - No Fees - Direct HR Email - Supreme Poultry Official - Equal Opportunity"
  },
 {
    title: "Site Administrator",
    company: "Afrimat Ash Resources",
    location: "Matla, Mpumalanga, South Africa",
    type: "Full-time - Mining",
    closing: "2026-09-25",
    description: "Provide day-to-day admin support to Site Manager. Compile daily/weekly/monthly reports, maintain site documentation, assist with purchase requisitions/orders/invoices, audit prep, receive/inspect/record stock/materials/PPE/tools, verify deliveries, store/issue stock, stock counts, monitor min/max levels. Requires Grade 12, Certificate in Administration/Stores/Logistics/Supply Chain advantageous, 2-3 years site admin/stores/warehouse exp, stock control, ERP system advantageous. Must be medically fit (Mine Health & Safety Act), valid driver's license, work under pressure, good leadership & communication.",
    link: "https://www.afrimat.co.za - Site Administrator Matla",
    verified: "Afrimat Ash Resources - Apply on website - Docs: CV + Certified ID + Matric in ONE file <3MB",
    requirements: "Grade 12 + Admin/Stores Certificate + 2-3 years exp + Stock Control + ERP + Driver's License + Medically Fit"
  },
 { 
    title: "Procurement Manager",
    company: "BKB Ltd",
    location: "Bethlehem, Free State",
    type: "Permanent",
    closing: "2026-09-09",
    description: "BKB Ltd Agriculture is hiring Procurement Manager - Bethlehem. Posted 19 August 2026. Primary purpose: Ensure efficient, cost-effective, and timely procurement of raw materials required for production, while upholding quality standards and fostering strong supplier relationships. Also responsible for implementing SAFEX hedging strategy and managing production planning and scheduling of client orders. Qualifications: 3 Year Qualification in Accounting, Supply Chain Management, Business Administration or related field, SAFEX trading exam beneficial, 3-7 years relevant experience. Skills: Excellent interpersonal and customer relations, Experience within production and logistical environment, Organised and logical problem-solving, Adapt quickly, Team player, General knowledge of accounting, Strong communication and admin, Management skills, Effective negotiation and stakeholder management. Key Responsibilities: Milldoor contract management, Manage Weighbridge Team, Manage SAFEX book and trading, Production Planning - Planning and scheduling of orders.",
    link: "https://bkb.simplify.hr/Vacancy/Apply/abc123",
    verified: "BKB Ltd Official Careers via Simplify.hr - Closing 09 September 2026"
  },
 {
    title: "FREE ARPL for Experienced Plumbers - Red Seal Certificate",
    company: "Motheo Academy x EWSETA",
    location: "Randburg, Johannesburg (Training) - National Applicants",
    type: "ARPL - Fully Funded - No Stipend",
    closing: "2026-09-11",
    description: "FREE Artisan Recognition of Prior Learning (ARPL) Opportunity for Experienced Plumbers - Re-advertisement. Motheo Academy in partnership with Energy and Water Sector Education and Training (EWSETA) offers Red Seal Certificate in Plumbing via ARPL. Requirements: Minimum 3 years plumbing work experience in South Africa, Grade 9 / Standard 7 minimum, Certified ID copy within last 3 months, Must be 19 years or older, Proof of work experience - service letter on company letterhead detailing at least six daily plumbing duties, period of service, signed by Director/CEO/HR/Manager, Self-employed must provide affidavit signed by Commissioner of Oaths + valid CK document, Must be currently employed and actively performing plumbing work, Detailed CV with contactable references, Must be available to attend training/practical sessions in Randburg JHB at own travel cost. Note: Fully funded, NO stipend payable.",
    link: "mailto:learnership@motheogroup.co.za",
    verified: "Verified via Motheo Academy LinkedIn Official - Closing 11 Sept 2026 - Enquiries 087 805 7474 - Ref EWSETA Partnership"
  },
 {
    title: "Maintenance Operator Mec",
    company: "Sasol",
    location: "Sasolburg, FS",
    province: "Free State",
    town: "Sasolburg",
    type: "On-site, Full-time",
    salary: "Sasol Official",
    ref: "Posting 26 Aug 2026 | Sasol",
    desc: "To support with maintenan",
    link: "https://www.sasol.com/car",
    verified: "✅ Verified - No Fee"
  },
 {
    title: "Parts Salesperson (Polokwane)",
    company: "AFGRI",
    location: "Polokwane, Limpopo",
    type: "Full-time",
    closing: "2026-09-04",
    description: "AFGRI is hiring Parts Salesperson - Ref AO-2454. Provide over-the-counter sales and administration functions of parts stock. Requirements: Grade 12, 1-year sales and administration experience, Parts sales experience essential, Construction parts sales knowledge advantage, Computer Literacy MS Office, Good customer service and communication, Valid Driver's Licence. Key duties: Ensure stable availability of stock by ordering in line with branch procedure, Conduct regular stock counting and stocktaking, Stock control and rotation, Build relationships with internal and external clients, Resolve customer queries and complaints, Accurate cash balancing, Process payments cash credit cards, Process sales and returns, Compliance with risk and safety legislation, Keep stock safe.",
    link: "https://www.afgri.co.za/vacancy/AO-2454",
    verified: "AFGRI Careers - Closing 04 September 2026"
  },
 {
    title: "Safety and Security Learnership (Persons with disability encouraged)",
    company: "Eagle Eye Security Specialist",
    location: "Ekurhuleni, Gauteng",
    type: "Learnership",
    closing: "2026-09-30",
    description: "Seeking applicants interested in Safety and Security Learnership programme. Persons with disability are encouraged to apply - inclusive opportunity for all. REQUIRED DOCUMENTS Submit as ONE PDF: Matric / Grade 12 Certificate, Detailed CV, Certified ID Copy, Confirmation of disability status (Medical report & Certificate). WARNING: DOUBLE DIPPING LEARNERSHIP NOT ALLOWED",
    link: "mailto:training2@eagle-ess.co.za?subject=Learnership Application - Ekurhuleni",
    verified: "Shared via SAJobs - Email: training2@eagle-ess.co.za"
  },
 {
    title: "Armed Dog Handlers - Red Ant",
    company: "Red Ant Security RASRE",
    location: "Limpopo - Polokwane, Giyani etc",
    province: "Limpopo",
    town: "Polokwane",
    type: "Full-time",
    salary: "Market Related",
    ref: "recruiting@rasre.co.za",
    desc: "Armed Dog Handlers & Armed Response",
    link: "mailto:recruiting@rasre.co.za",
    verified: "✅ Verified - No Fee"
  },
 { 
    title: "Work Integrated Learning (WIL) - Non Technical",
    company: "Transnet SOC Ltd",
    location: "Koedoespoort, Germiston, Bloemfontein, Durban, Uitenhage and Saltriver",
    type: "Learnership - WIL Programme",
    closing: "2026-08-20",
    description: "Transnet Non Technical WIL Programme which aligns to Transnet Business Strategy. Non-Technical Disciplines: Human Resource Management, Office Management. Minimum Requirements: Matric certificate and completed theoretical N4 - N6 for HR and Office Management, Must be South African, Age between 18-35, Preference for people with Disability, No bursary obligation with other company. Required docs: Inservice training Letter from Institution for WIL Programme, Proof of certified Matric certificate and ID, Full Academic record, updated CV, Grade 12 report, full academic transcript.",
    link: "https://www.transnet.net/careers",
    verified: "Shared via SAJobs - Transnet Academy"
   },
  {
    title: "Security Officers - Phangela Group",
    company: "Phangela Group",
    location: "Cape Town",
    province: "Western Cape",
    town: "Goodwood",
    type: "Full-time",
    closing: "2026-08-31",
    description: "Security Officers Senior Grade B"
  },
  {
    title: "Receptionist / Adminis",
    company: "Fidelity Services Group",
    location: "Rustenburg, North West",
    type: "Full-time",
    closing: "2026-08-28",
    description: "Manage reception and"
 }, 
 {
  title: "Cleaner",
  company: "Food Lover's Market",
  location: "Bruma, Gauteng",
  type: "Full-time",
  closing: "2026-09-30",
  description: "Cleaning floors, restrooms, waste management, cleaning supplies. Grade 12, previous cleaner/general worker experience, clear criminal record.",
  link: "https://www.sajobsportal.co.za",
  verified: "Shared via SAJobsPortal"
},
{
  title: "Cashiers (X4 Posts)",
  company: "Food Lover's Market",
  location: "Tokai, Kuils River, Hermanus - WC",
  type: "Full-time",
  closing: "2026-09-30",
  description: "Operate POS, scan purchases, handle cash/card payments. Grade 12 + Cashier experience + POS system experience.",
  link: "https://www.sajobsportal.co.za",
  verified: "Shared via SAJobsPortal"
},
{
  title: "Cashiers (X10 Posts)",
  company: "Pedros Flame Grilled Chicken",
  location: "Various - South Africa",
  type: "Full-time",
  closing: "2026-09-30",
  description: "Welcome customers, take orders, handle payments, maintain service areas. Customer-focused, busy restaurant environment.",
  link: "https://www.sajobsportal.co.za",
  verified: "Shared via SAJobsPortal"
},
{
  title: "Waiter / Waitress",
  company: "RocoMamas",
  location: "Krugersdorp, Gauteng",
  type: "Full-time",
  closing: "2026-09-30",
  description: "Welcome guests, explain menu, take orders, serve food, process payments. Previous waiter experience, English communication, clear criminal record.",
  link: "https://www.sajobsportal.co.za",
  verified: "Shared via SAJobsPortal"
},
{
  title: "Cleaners (X11 Posts) - No Experience",
  company: "DPSA - Department of Transport",
  location: "Ladysmith & Durban, KZN",
  type: "Government",
  closing: "2026-08-31",
  description: "11 Cleaner vacancies. Government DPSA posting. No experience needed. Must be SA citizen.",
  link: "https://www.sajobsportal.co.za",
  verified: "Government post via SAJobsPortal - check DPSA Circular"
},
{
  title: "McDonald's Learnerships (X30) - No Experience",
  company: "McDonald's SA",
  location: "Various Provinces",
  type: "Learnership",
  closing: "2026-08-30",
  description: "Cohort 2 Learnership. Grade 12, 18-26 years, SA citizen, unemployed, not studying, clear criminal record, willing to work shifts.",
  link: "https://www.sajobsportal.co.za",
  verified: "Shared via SAJobsPortal"
},
{
  title: "FREE Government Job Matching - ESSA System",
  company: "Department of Employment & Labour - Bethlehem Labour Centre",
  location: "36 Louw Street, Bethlehem 9700 - For ALL Dihlabeng (Paul Roux, Fouriesburg, Clarens)",
  province: "Free State",
  type: "FREE Registration - No Closing Date",
  salary: "FREE - MAHALA",
  closing: "Open Everyday",
  badge: "VERIFIED GOVERNMENT - FREE",
  link: "https://www.labour.gov.za",
  phone: "058-3035297 / 082 072 6812",
  email: "Dimakatso.mokoena@labour.gov.za",
  description: "ESSA will match your CV automatically to employers. Register once at Labour Centre. They have Formal Jobs, Learnerships, Apprenticeships, Internships. Bring ID, CV, Qualifications. Ask for SENIOR EMPLOYMENT PRACTITIONER Mokoena DE. All services are FREE per UI Act.",
  isReal: true
},
{
    title: "Presiding Officer / Deputy Presiding Officer",
    company: "IEC - Electoral Commission of South Africa",
    location: "Dihlabeng Local Municipality FS192 - Bethlehem, Paul Roux, Fouriesburg, Clarens",
    province: "Free State",
    type: "Temporary Election Contract",
    salary: "R3,580 - R4,500 (per event)",
    closing: "2026-08-31",
    badge: "VERIFIED - OFFICIAL IEC SITE",
    link: "https://www.elections.org.za/pw/About-Us/BrowseJobs",
    applyLink1: "https://registertovote.elections.org.za/account/create",
    applyLink2: "https://online.elections.org.za/MyIEC",
    requirements: "SA Citizen, Registered Voter, 8 Years Exp, No Political Office Last 5 Years, Smartphone, Bank Account, SARS",
    description: "OFFICIAL IEC SITE ONLY. Create profile at registertovote.elections.org.za then apply at elections.org.za. Temporary work: 2 special voting days + voting day + counting. Must have Sesotho & English. Upload CV, ID, Qualifications, Bank Statement, SARS.",
    isReal: true,
    officialSite: "www.elections.org.za - NOT iec.org.za (fake)"
  },
  {
    title: "Retail Associate",
    company: "BKB",
    location: "Stutterheim, EC",
    province: "Eastern Cape",
    town: "Stutterheim",
    type: "Full-time | On-site",
    salary: "Market Related",
    ref: "Published: 27 Aug 2026 | Closing: 03 September 2026",
    desc: "Current Vacancy at BKB - Retail Associate. Location: Stutterheim, Eastern Cape. Retail operations and customer service.",
    link: "https://bkb.simplify.hr/",
    verified: "✅ Verified - BKB Official"
  },
  {
    title: "2x Shipping Forklift Drivers",
    company: "BKB",
    location: "Gqeberha / Port Elizabeth, EC",
    province: "Eastern Cape",
    town: "Gqeberha",
    type: "Full-time | On-site",
    salary: "Market Related",
    ref: "Published: 21 Aug 2026 | Closing: 27 August 2026",
    desc: "Current Vacancy at BKB - 2x Shipping Forklift Drivers. Location: Gqeberha/Port Elizabeth. Must have valid forklift license and shipping experience.",
    link: "https://bkb.simplify.hr/",
    verified: "✅ Verified - BKB Official"
  },
  {
    title: "Procurement Manager",
    company: "BKB",
    location: "Bethlehem, FS",
    province: "Free State",
    town: "Bethlehem",
    type: "Full-time | On-site",
    salary: "Market Related",
    ref: "Published: 19 Aug 2026 | Closing: 09 September 2026",
    desc: "Current Vacancy at BKB - Procurement Manager. Location: Bethlehem, Free State. Procurement and supply chain management.",
    link: "https://bkb.simplify.hr/",
    verified: "✅ Verified - BKB Official"
  },
  {
    title: "Clerk, Steel Making & Final Products, Vanderbijlpark (A2)",
    company: "ArcelorMittal South Africa",
    location: "Vanderbijlpark, GP",
    province: "Gauteng",
    town: "Vanderbijlpark",
    type: "Permanent | On-site",
    salary: "Market Related",
    ref: "arcmt_000923 | Apply by: 2 September 2026",
    desc: "Industry: Steel Industry | Job category: Admin, Office Support and Services | Contract: Permanent | EE position: No | Part of the worldwide ArcelorMittal group.",
    link: "https://arcelormittalsa.ci.hr",
    verified: "✅ Verified - No Fee - ArcelorMittal Official"
  },
  {
    title: "Seasonal Sales Associate Opportunity (No Matric)",
    company: "TFG - The Foschini Group",
    location: "South Africa - Nationwide | Sportscene, Totalsports, Sneaker Factory, Archive, Jet",
    province: "All Provinces",
    town: "Nationwide",
    type: "Contract | Retail 120hr",
    salary: "Market Related - Seasonal",
    ref: "Job ID: 14398 | Posted 2026 | No Matric Needed",
    desc: "TFG is looking for fun, energetic, hardworking SEASONAL employees. Brands: Bloo, Sportscene, Totalsports, Sneaker Factory, Archive, Jet. No Matric required! Must be SA Citizen, good communication & selling skills, willing to work retail hours including weekends. Apply online only.",
    link: "https://fa-expc-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/14398",
    verified: "✅ Verified - TFG Official Oracle"
  },
  {
    title: "Apprenticeship Opportunity X40",
    company: "AFGRI Equipment - John Deere",
    location: "South Africa - Bethlehem, Harrismith, Frankfort & 37 more",
    province: "Free State",
    town: "Bethlehem",
    type: "Apprenticeship - 3 Years",
    salary: "Stipend + Training",
    ref: "AO-2345 | Closing 30 Sept 2026",
    desc: "AFGRI Equipment has proudly held the John Deere Agency since 1962. 40x Tractor/Earthmoving Apprentices. Matric with English & Maths (NOT Maths Lit) + Driver's Licence required.",
    link: "https://afgri.erecruit.co/candidateapp/Jobs/Browse",
    verified: "✅ Verified"
  },
  {
    title: "Leerder Program / Learnership Programme 2027",
    company: "OOS VRYSTAAT KAAP BEDRYF BPK",
    location: "Paul Roux, Free State",
    province: "Free State",
    town: "Paul Roux",
    type: "Learnership - Handel Noord",
    salary: "Learnership",
    ref: "OVK Paul Roux",
    desc: "Uitstekende geleentheid vir Matrieks!",
    link: "https://www.ovk.co.za/careers",
    verified: "✅ Verified - OVK Official"
  },
  {
    title: "Administrative Clerk (Admin Clerk)",
    company: "Department of Water and Sanitation",
    location: "Bloemfontein",
    salary: "R237 453 per year",
    type: "Full-time | Admin",
    ref: "Ref No: 270826/06 | Grade 12 + Admin | DWS Bloem",
    link: "https://www.dws.gov.za/"
  },
  {
    title: "Truck Driver Learnership Programme",
    company: "Unitrans",
    location: "KZN, Cape Town, Gauteng - Nationwide",
    salary: "Learnership Stipend",
    type: "Learnership | Logistics",
    ref: "Grade 12 | No Experience | Unitrans 2026",
    link: "https://www.unitransafrica.com/"
  },
  {
    title: "Teller - Bethlehem",
    company: "Fidelity Services Group",
    location: "Bethlehem, Free State",
    salary: "Permanent",
    type: "Permanent | Operations",
    ref: "Clear Criminal Record | Grade 12 | 2 Years Cashier | Fidelity",
    link: "https://fidelityservicesgroup.simplify.hr/"
  },
  {
    title: "Learner Programme / Learnership 2026",
    company: "OVK",
    location: "Fouriesburg, Free State",
    salary: "Contract - Learnership",
    type: "Learnership | Handel Noord",
    ref: "Vrystaat | Fouriesburg | Kontrak | Grade 12 | OVK",
    link: "https://www.ovk.co.za/"
  },
  {
    title: "Systems Controller - Qpro Feeds",
    company: "VKB Group / Qpro Feeds",
    location: "Bethlehem, Free State",
    salary: "Market Related",
    type: "Permanent | IT",
    ref: "VKB Bethlehem | IT Degree | Systems",
    link: "https://www.vkb.co.za/"
  },
  {
    title: "General Worker - VKB Retail",
    company: "VKB Group",
    location: "Villiers, Free State",
    salary: "Entry Level",
    type: "Permanent | Grade 12",
    ref: "VKB Villiers | General Worker",
    link: "https://www.vkb.co.za/"
  },
  {
    title: "Cashier - VKB Retail",
    company: "VKB Group",
    location: "Frankfort, Free State",
    salary: "Retail",
    type: "Permanent | Retail",
    ref: "VKB Frankfort | Cashier",
    link: "https://www.vkb.co.za/"
  },
  {
    title: "Admin Clerk",
    company: "OVK Group",
    location: "Reitz, Free State",
    salary: "Admin - R9,500",
    type: "Permanent | Admin",
    ref: "OVK Reitz | Admin Clerk",
    link: "https://www.ovk.co.za/"
  },
  {
    title: "Shop Assistant",
    company: "OVK Retail",
    location: "Memel, Free State",
    salary: "Retail",
    type: "Permanent | Retail",
    ref: "OVK Memel | Shop Assistant",
    link: "https://www.ovk.co.za/"
  },
  {
    title: "Forklift Operator",
    company: "VKB Group",
    location: "Bethlehem, Free State",
    salary: "R12,000",
    type: "Permanent | Operator",
    ref: "VKB | Forklift License",
    link: "https://www.vkb.co.za/"
  },
  {
    title: "Cleaner",
    company: "Fidelity Services",
    location: "Harrismith, Free State",
    salary: "Entry Level - R7,000",
    type: "Permanent | Grade 10",
    ref: "Fidelity | Cleaner | Harrismith",
    link: "https://fidelityservicesgroup.simplify.hr/"
  },
  {
    title: "Security Guard",
    company: "Fidelity ADT",
    location: "Bethlehem, Free State",
    salary: "PSIRA Grade C",
    type: "Contract | Security",
    ref: "Fidelity ADT | PSIRA | Bethlehem",
    link: "https://fidelityservicesgroup.simplify.hr/"
  },
  {
    title: "Driver - Code 10 + PDP",
    company: "VKB Group",
    location: "Free State",
    salary: "Driving - R15,000",
    type: "Permanent | Driver",
    ref: "VKB | Code 10 | PDP",
    link: "https://www.vkb.co.za/"
  }
];

function showJobs(){
  let container=document.getElementById("jobs") || document.getElementById("jobs-container");
  if(!container){
    container=document.createElement("div");
    container.id="jobs";
    container.style.padding="10px";
    document.body.appendChild(container);
  }
  let html = `<h2 style="font-family:sans-serif;text-align:center;color:#1b5e20;">🔥 ${jobs.length} JOBS LIVE - Job Seeker SA 🔥</h2>`;
  jobs.forEach(job=>{
    html += `
    <div style="border:2px solid #2e7d32;padding:16px;margin:12px 0;border-radius:14px;background:white;font-family:sans-serif;">
      <h3 style="margin:0 0 8px 0;color:#1b5e20;">${job.title}</h3>
      <p style="margin:4px 0;"><b>${job.company}</b> - ${job.location}</p>
      <p style="margin:4px 0;color:#444;">💰 ${job.salary || ''} | 📄 ${job.type || ''}</p>
      <p style="font-size:13px;color:#666;margin:6px 0;">${job.ref || ''} ${job.verified || ''}</p>
      <p style="font-size:14px;">${job.desc || ''}</p>
      <a href="${job.link}" target="_blank" style="display:inline-block;background:#2e7d32;color:white;padding:12px 22px;border-radius:10px;text-decoration:none;font-weight:bold;margin-top:10px;">✅ APPLY NOW</a>
    </div>`;
  });
  container.innerHTML=html;
}
document.addEventListener("DOMContentLoaded", showJobs);
showJobs();
